//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Word Aid 2.rc
//
#define IDS_WORDAID2                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WORDAID2_DIALOG             102
#define IDS_WORD_ADD                    102
#define IDS_WORD_EDIT                   103
#define IDS_ABBREV_EDIT_TXT             104
#define IDS_ABBREV_ADD_TXT              105
#define IDS_ERR_NO_ABBREVIATION_ENTERED 106
#define IDS_ERR_NO_EXPANSION_ENTERED    107
#define IDS_MENU_OPEN_ALPHA             108
#define IDS_MENU_OPEN_TOPIC             109
#define IDS_MENU_OPEN_ABBREV            110
#define IDS_WORDAID_EDIT_ADD            111
#define IDS_WORDAID_EDIT_EDIT           112
#define IDS_WORDAID_EDIT_DELETE         113
#define IDS_ABBREV_EDIT_ADD             114
#define IDS_ABBREV_EDIT_EDIT            115
#define IDS_ABBREV_EDIT_DELETE          116
#define IDS_ABBREV_EXT_TEST             117
#define IDS_SAVE_CHANGES_ABBREV         118
#define IDS_ERROR_LOADING_FILE          119
#define IDS_ABBREV_BUTTON               120
#define IDS_WORDAID_TITLE               121
#define IDS_FILEOPEN_ERROR              122
#define IDS_ALPHA_EXT_OLD               123
#define IDS_ERROR_FILETYPE              124
#define IDS_SETTINGS_UPDATED            125
#define IDS_SETTINGS_ERROR              126
#define IDS_TEXT_EXT                    127
#define IDR_MAINFRAME                   128
#define IDS_TEXT_EXT_ADD                128
#define IDR_MAIN_MENU                   129
#define IDS_DELETE_ABBREV               129
#define IDD_DIALOG1                     130
#define IDD_ADDWORD_DLG                 130
#define IDS_BTN_OK                      130
#define IDD_DUMMY_DLG                   131
#define IDS_BTN_CANCEL                  131
#define IDD_POPUP_SETTINGS              132
#define IDD_BUTTON_SETTINGS             132
#define IDS_FUNC_KEYS                   132
#define IDD_TREE_DIALOG                 133
#define IDS_NUM_KEYS                    133
#define IDD_WORD_SETTINGS               134
#define IDS_NUMPAD_KEYS                 134
#define IDS_NO_KEYS                     135
#define IDD_KEY_SETTINGS                136
#define IDS_CANNOT_SET                  136
#define IDB_BMP_SETTING_TREE            137
#define IDS_SELECT_WORD_SAME            137
#define IDD_GENERAL_SETTINGS            138
#define IDS_UNDO_SAME                   138
#define IDS_SHOWLIST_SAME               139
#define IDR_ACCELERATOR1                140
#define IDS_ABBREV_MANUAL_SAME          140
#define IDS_UNEXPAND_FULL_SAME          141
#define IDS_UNEXPAND_PART_SAME          142
#define IDD_ADD_DELETE_DLG              143
#define IDS_SELECT_WORD_TYPE            143
#define IDS_UNDO_TYPE                   144
#define IDS_SHOWLIST_TYPE               145
#define IDS_ABBREV_MANUAL_TYPE          146
#define IDD_EDITWORD_DLG                147
#define IDS_UNEXPAND_FULL_TYPE          147
#define IDD_SPEECH_DLG                  148
#define IDS_UNEXPAND_PART_TYPE          148
#define IDD_SPEECH_SETUP                150
#define IDD_ABBREV_EXPANSION            152
#define IDD_ADD_EDIT_ABBREV             155
#define IDS_FILETYPE_ABBREV             156
#define IDS_FILETYPE_ALL_ABBREV         157
#define IDR_MAIN_TOOLBAR                157
#define IDS_FILETYPE_ABBREV_ALL         158
#define IDI_ICON1                       161
#define IDD_DLG_WORD_SELECT             162
#define IDD_DLG_FILE_SELECT             164
#define IDB_BITMAP_MERGE                166
#define IDD_DLG_MERGE_INTRO             167
#define IDD_DLG_MERGE_TYPE              168
#define IDR_WORDLIST_MENU               170
#define IDD_WORDAID                     171
#define IDD_ADVANCED_KEYS_DLG           172
#define IDD_NEWLISTDLG                  173
#define IDB_BMP_ARROW_DOWN              174
#define IDB_BMP_ARROW_UP                175
#define IDB_ALPHA_LIST                  181
#define IDB_TOPIC_LIST                  182
#define IDB_ABBREV_LIST                 184
#define IDB_BMP_STOP                    186
#define IDC_LIST_WORDLIST               1000
#define IDC_LBL_VERSION                 1001
#define IDC_EDIT1                       1001
#define IDC_BTN_SORT_ALPHA              1002
#define IDC_EDIT_RATE                   1002
#define IDC_EDIT2                       1002
#define IDC_EDT_PART_EXPAN_HOTKEY       1002
#define IDC_EDT_EXPAN                   1002
#define IDC_EDIT_MAXWORD                1002
#define IDC_EDIT_FILE2                  1002
#define IDC_EDT_NEW                     1002
#define IDC_TAB_WORDLIST                1003
#define IDC_EDIT_PITCH                  1003
#define IDC_EDIT_FILE_OUT               1003
#define IDC_EDT_PART_EXPAN_HOTKEY1      1003
#define IDC_CMB_POPUP_SETTING           1004
#define IDC_CMB_COLOUR                  1005
#define IDC_CMB_FONT_NAME               1006
#define IDC_CMB_FONT_COLOUR             1007
#define IDC_CMB_FONT_SIZES              1010
#define IDC_BTN_CUSTOM_COLOUR           1012
#define IDC_BTN_CUSTOM_FONT_COLOUR      1013
#define IDC_BTN_CUSTOM_HIGHLIGHT_COLOUR 1014
#define IDC_BTN_APPLY                   1016
#define IDC_OK                          1017
#define IDC_CANCEL                      1018
#define IDC_CMB_HIGHLIGHT_COLOUR        1019
#define IDC_CMB_SELECT_WORD             1020
#define IDC_CHK_SELECT_WORD_SHIFT       1021
#define IDC_CHK_SELECT_WORD_CTRL        1022
#define IDC_CHK_SELECT_WORD_ALT         1023
#define IDC_CMB_UNDO                    1024
#define IDC_CHK_UNDO_SHIFT2             1025
#define IDC_CHK_UNDO_CTRL               1026
#define IDC_CHK_UNDO_ALT                1027
#define IDC_CHK_SHOW_LIST_HOTKEY        1028
#define IDC_CMB_SHOW_LIST_HOTKEY        1029
#define IDC_TREE1                       1029
#define IDC_CHK_SHOW_LIST_SHIFT3        1030
#define IDC_CHK_AUTO_SPACE              1030
#define IDC_CHK_SHOW_LIST_CTRL2         1031
#define IDC_CHK_AUTO_CAP                1031
#define IDC_CHK_SHOW_LIST_ALT2          1032
#define IDC_CHK_MINIMIZE                1032
#define IDC_CHECK4                      1033
#define IDC_CHK_STICKY_SHIFT            1033
#define IDC_CHK_SHIFT                   1033
#define IDC_COMBO_MAXWORDS              1034
#define IDC_CHK_CTRL                    1034
#define IDC_STATIC_KEYS                 1035
#define IDC_CHK_AUTO_SPACE_WORD         1035
#define IDC_CHK_ALT                     1035
#define IDC_BTN_IDOK                    1036
#define IDC_CHK_ALPHA                   1041
#define IDC_CHK_TOPIC                   1043
#define IDC_STATIC_5                    1044
#define IDC_BTN_ADDWORD                 1047
#define IDC_TEXTSPEAKER1                1048
#define IDC_CHK_SPEECHON                1049
#define IDC_COMBO_VOICE                 1050
#define IDC_SLIDER_VOL                  1051
#define IDC_SLIDER_RATE                 1052
#define IDC_SLIDER_PITCH                1053
#define IDC_BTN_TEST                    1054
#define IDC_EDIT_VOL                    1055
#define IDC_CHK_SPEAKALL                1056
#define IDC_DWELL_ALL                   1057
#define IDC_DWELL_SELECTED              1058
#define IDC_RAD_AUTO_AFTER              1060
#define IDC_EDT_AUTO_AFTER              1061
#define IDC_RAD_SEMI_AUTO               1063
#define IDC_RAD_MANUAL                  1064
#define IDC_EDT_MANUAL_HOTKEY           1065
#define IDC_CHK_LISTED_EXPAN            1067
#define IDC_CHK_WORD_BANK               1068
#define IDC_EDT_FULL_EXPAN_HOTKEY       1069
#define IDC_EDT_FULL_EXPAN_HOTKEY1      1069
#define IDC_EDT_ABBREV                  1071
#define IDD_BTN_ADD                     1075
#define IDC_CHK_ABBREV_ON               1077
#define IDC_CHECK1                      1079
#define IDC_CHK_WORDAID                 1079
#define IDC_CHK_SELECTION               1079
#define IDC_CHK_HIDE_LIST               1079
#define IDC_CHK_BUTTON_BITMAPS          1079
#define IDC_EDIT_MINWORD                1080
#define IDC_LIST_INPUT                  1081
#define IDC_LIST_OUTPUT                 1082
#define IDC_BTN_WORD_IN                 1083
#define IDC_RADIO_MERGE_ALL             1084
#define IDC_BTN_WORD_OUT                1084
#define IDC_RADIO_MERGE_SELECTED        1085
#define IDC_BTN_ALL_IN                  1085
#define IDC_BTN_BROWSE_FILE1            1086
#define IDC_BTN_ALL_OUT                 1086
#define IDC_BTN_BROWSE_FILE2            1087
#define IDC_BTN_BROWSE_OUTPUT           1088
#define IDC_TXT_OUTPUT_FILE             1089
#define IDC_TXT_INPUT_FILE              1090
#define IDC_EDIT_FILE1                  1091
#define IDC_EDT_UNDO_HOTKEY             1092
#define IDC_EDT_SHOW_LIST_KEY           1093
#define IDC_BTN_DEFAULT                 1094
#define IDC_BTN_SAY                     1095
#define IDC_BTN_LEXICON                 1096
#define IDC_BTN_SAY_ABBREV              1097
#define IDC_BTN_SAY_EXPAN               1098
#define IDC_LST_KEYS                    1100
#define IDC_CMB_USED_BY                 1101
#define IDC_EDT_CURRENT                 1102
#define IDC_BTN_ASSIGN                  1103
#define IDC_EDT_DESCRIPTION             1104
#define IDC_BTN_ADVANCED                1105
#define IDC_LIST_TYPE                   1107
#define IDC_CHK_FIRSTAUTO               1110
#define ID_FILE_NEWWORDLIST             32771
#define ID_FILE_OPENALPHABETIC          32773
#define ID_FILE_OPENTOPIC               32774
#define ID_FILE_EXIT                    32776
#define ID_EDIT_ADDWORD                 32777
#define ID_EDIT_EDITWORD                32778
#define ID_FILE_SAVEAS                  32779
#define ID_SETTINGS_POPUPSETTINGS       32782
#define ID_EDIT_DELETEWORD              32783
#define ID_SAVESETTINGS                 32784
#define ID_LOADSETTINGS                 32785
#define ID_SETTINGS_TOOLBAR             32786
#define ID_BUTTON32790                  32790
#define ID_MERGE_FILES                  32795
#define ID_RIGHT_SORTED                 32799
#define ID_RIGHT_SAYWORD                32800
#define ID_RIGHT_LEXICON                32801
#define ID_SETTINGS_LEXICON             32802
#define ID_FILE_OPENABBREV              32803
#define IDS_ALPHA_WORDLIST              57608
#define IDS_TOPIC_WORDLIST              57609
#define IDS_ABBREV_WORDLIST             57610
#define IDS_SAVE_SETTING                57611
#define IDS_UP_WORDLIST                 61204
#define IDS_DOWN_WORDLIST               61205
#define IDS_FILETYPE_ALPHA              61206
#define IDS_FILETYPE_TOPIC              61207
#define IDS_FILETYPE_ALL                61208
#define IDS_TOPIC_EXT                   61209
#define IDS_ALPHA_EXT                   61210
#define IDS_BUTTON_FONT                 61211
#define IDS_TOPIC_EXT_TEST              61211
#define IDS_FONT_SIZES                  61212
#define IDS_BUTTON_BACKGROUND           61213
#define IDS_NO_MATCH                    61213
#define IDS_TEXT_FONT                   61214
#define IDS_ALPHA_EXT_TEST              61214
#define IDS_TEXT_BACKGROUND             61215
#define IDS_NO_DUPLICATES               61215
#define IDS_NO_WORD_SELECTED            61216
#define IDS_SAVE_CHANGES                61217
#define IDS_SAVE_CHANGES_ALPHA          61217
#define IDS_SAVE_CHANGES_TOPIC          61218
#define IDS_INSERT_WORD                 61219
#define IDS_DELETE_WORD                 61220
#define IDS_NOT_FOUND                   61221
#define IDS_TEST_STRING                 61222
#define IDS_SETTING_SETTING             61223
#define IDS_SETTING_GENERAL             61224
#define IDS_SETTING_BUTTONS             61225
#define IDS_SETTING_WORDLIST            61226
#define IDS_SETTING_HOTKEYS             61227
#define IDS_SETTING_WORDAID             61228
#define IDS_SETTING_WORDAID1            61229
#define IDS_SETTING_ABBREV              61230
#define IDS_SETTING_EXPANSION           61231
#define IDS_SETTING_SPEECH              61232
#define IDS_SETTING_SPEECH_SETUP        61233
#define IDS_SETTING_VOICE_SETUP         61234
#define IDS_KEYBOARD_WORDLIST           61235
#define IDS_KEYBOARD_ADD                61236
#define IDS_KEYBOARD_DELETE             61237
#define IDS_KEYBOARD_ADD_DES            61238
#define IDS_KEYBOARD_DELETE_DES         61239
#define IDS_KEYBOARD_SAYWORD            61240
#define IDS_KEYBOARD_SAYWORD_DES        61241
#define IDS_KEYBOARD_INSERT             61242
#define IDS_KEYBOARD_INSERT_DES         61243
#define IDS_KEYBOARD_PAGEUP             61244
#define IDS_KEYBOARD_PAGEUP_DES         61245
#define IDS_KEYBOARD_PAGEDWN            61246
#define IDS_KEYBOARD_PAGEDWN_DES        61247
#define IDS_KEYBOARD_UPARROW            61248
#define IDS_KEYBOARD_UPARROW_DES        61249
#define IDS_KEYBOARD_DWNARROW           61250
#define IDS_KEYBOARD_DWNARROW_DES       61251
#define IDS_KEYBOARD_LFTARROW           61252
#define IDS_KEYBOARD_LFTARROW_DES       61253
#define IDS_KEYBOARD_RGHTARROW          61254
#define IDS_KEYBOARD_RGHTARROW_DES      61255
#define IDS_KEYBOARD_UNDO               61256
#define IDS_KEYBOARD_UNDO_DES           61257
#define IDS_KEYBOARD_SHOWLIST           61258
#define IDS_KEYBOARD_SHOWLIST_DES       61259
#define IDS_KEYBOARD_UNDOPART           61260
#define IDS_KEYBOARD_UNDOPART_DES       61261
#define IDS_KEYBOARD_UNDOFULL           61262
#define IDS_KEYBOARD_UNDOFULL_DES       61263
#define IDS_ADD_WORD_TYPE               61264
#define IDS_DELETE_WORD_TYPE            61265
#define IDS_INSERT_TYPE                 61266
#define IDS_SAY_TYPE                    61267
#define IDS_PAGEUP_TYPE                 61268
#define IDS_PAGEDWN_TYPE                61269
#define IDS_UPARR_TYPE                  61270
#define IDS_DWNARR_TYPE                 61271
#define IDS_LEFTARR_TYPE                61272
#define IDS_RIGHTARR_TYPE               61273
#define IDS_ADD_WORD_SAME               61274
#define IDS_DELETE_WORD_SAME            61275
#define IDS_INSERT_SAME                 61276
#define IDS_SAY_SAME                    61277
#define IDS_PAGEDWN_SAME                61278
#define IDS_PAGEUP_SAME                 61279
#define IDS_UPARR_SAME                  61280
#define IDS_DWNARR_SAME                 61281
#define IDS_LEFTARR_SAME                61282
#define IDS_RIGHTARR_SAME               61283
#define IDS_KEYBOARD_SELECTWORD         61284
#define IDS_KEYBOARD_ABBREVMAN          61285
#define IDS_NEW_ABBREV_LIST             61286
#define IDS_NEW_ALPHA_LIST              61287
#define IDS_NEW_TOPIC_LIST              61288
#define IDS_NO_KEYHOOK_DLL              61289
#define IDS_NO_SAPI                     61290
#define IDS_MAXWORDLENGTH_ERROR         61291
#define IDS_MINWORDLENGTH_ERROR         61292
#define IDS_ERR_MAX_WORD                61293
#define IDS_ERR_SELECT_KEYS             61294
#define IDS_DEMO_OPEN                   61295
#define IDS_DEMO_SAVE                   61296
#define IDS_ABBREV_BTN_HK               61297
#define IDS_ABBREV_BTN_HK_DES           61298
#define IDS_ABBREVBTN_TYPE              61299
#define IDS_ABBREVBTN_SAME              61300
#define IDS_STOP_WORDLIST               61301
#define IDS_NONE_ABOVE                  61302
#define IDS_NONE_BELOW                  61303
#define IDS_DEMO_NEW                    61304
#define IDS_FILE_OPEN_STR               61305
#define IDS_FILE_SAVE_STR               61306
#define IDS_WORDLENGTH_ERR              61307
#define IDS_ABBREV_BTN_ALPHA            61308
#define IDS_ABBREV_BTN_TOPIC            61309

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
