#if !defined(AFX_TEXTSPEAKER_H__AD305D17_F7EB_4A93_B203_0983082C1730__INCLUDED_)
#define AFX_TEXTSPEAKER_H__AD305D17_F7EB_4A93_B203_0983082C1730__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTextSpeaker wrapper class

class CTextSpeaker : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTextSpeaker)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x91e94be8, 0x9a24, 0x11d1, { 0xb0, 0x4e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL CanShowAboutDialog();
	BOOL CanShowGeneralDialog();
	BOOL CanShowLexiconDialog();
	BOOL CanShowTranslateDialog();
	void ClearSavedVoice(LPCTSTR configuration);
	LPDISPATCH GetCurrentVoice();
	long GetPitch();
	long GetRealTime();
	long GetSpeed();
	LPDISPATCH GetVoice(long index);
	long GetVoiceCount();
	long GetVolume();
	BOOL IsSpeechAvailable();
	void Pause();
	void RestoreVoice(LPCTSTR configuration);
	void Resume();
	void SaveVoice(LPCTSTR configuration);
	BOOL SelectVoice(LPDISPATCH voice);
	void SetPitch(long pitch);
	void SetRealTime(long percent);
	void SetSpeed(long speed);
	void SetVolume(long volume);
	void ShowAboutDialog(long parent_window);
	void ShowGeneralDialog(long parent_window);
	void ShowLexiconDialog(long parent_window);
	void ShowTranslateDialog(long parent_window);
	void Speak(LPCTSTR text);
	void Stop();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEXTSPEAKER_H__AD305D17_F7EB_4A93_B203_0983082C1730__INCLUDED_)
